"""Add postedAt and user_id column.

Revision ID: 148430c617b2
Revises: e043be85fa0e
Create Date: 2019-05-27 07:24:08.172655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148430c617b2'
down_revision = 'e043be85fa0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('postedAt', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'postedAt')
    # ### end Alembic commands ###
