"""Remove pitch_test column from users table.

Revision ID: 546b964dab90
Revises: b7ab7d3951a6
Create Date: 2019-05-27 22:21:25.537219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546b964dab90'
down_revision = 'b7ab7d3951a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pitch_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
