"""- Add posted_by field to Comment model.

Revision ID: 781aa3c8f822
Revises: 001ac689353b
Create Date: 2020-08-10 15:38:22.974894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781aa3c8f822'
down_revision = '001ac689353b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted_by')
    # ### end Alembic commands ###
