"""Remove pass-secure column from users table.

Revision ID: 785a056f76fa
Revises: 7e18c56b7786
Create Date: 2019-05-26 10:33:21.903926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785a056f76fa'
down_revision = '7e18c56b7786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
