"""Add posted_by column

Revision ID: 9e76e7270874
Revises: 9df963dd3fed
Create Date: 2019-05-28 06:36:58.700531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e76e7270874'
down_revision = '9df963dd3fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted_by')
    # ### end Alembic commands ###
