"""AdAdd title column to comments table.

Revision ID: b7ab7d3951a6
Revises: 148430c617b2
Create Date: 2019-05-27 09:03:53.702103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ab7d3951a6'
down_revision = '148430c617b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###
