"""empty message

Revision ID: dbd431e6b2b6
Revises: 1052c3d8f976
Create Date: 2019-05-26 17:43:16.874755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd431e6b2b6'
down_revision = '1052c3d8f976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_table', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_table', 'category')
    # ### end Alembic commands ###
