"""empty message

Revision ID: e043be85fa0e
Revises: c865b673c45f
Create Date: 2019-05-26 19:20:49.550526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e043be85fa0e'
down_revision = 'c865b673c45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pitch_test')
    # ### end Alembic commands ###
